//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace projectBase.WSAlzaArchivos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="extractosSoap", Namespace="http://10.1.1.191/extractosService.asmx")]
    public partial class extractos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback extractoCuentaServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback extractoCuentaConEntidadServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarDirectorioOperationCompleted;
        
        private System.Threading.SendOrPostCallback alzarArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback bajarArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback alzarArchivoPASOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaArchivosPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback bajarArchivoPASOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminaArchivoPASOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public extractos() {
            this.Url = global::projectBase.Properties.Settings.Default.projectBase_WSAlzaArchivos_extractos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event extractoCuentaServiceCompletedEventHandler extractoCuentaServiceCompleted;
        
        /// <remarks/>
        public event extractoCuentaConEntidadServiceCompletedEventHandler extractoCuentaConEntidadServiceCompleted;
        
        /// <remarks/>
        public event eliminarDirectorioCompletedEventHandler eliminarDirectorioCompleted;
        
        /// <remarks/>
        public event alzarArchivoCompletedEventHandler alzarArchivoCompleted;
        
        /// <remarks/>
        public event bajarArchivoCompletedEventHandler bajarArchivoCompleted;
        
        /// <remarks/>
        public event alzarArchivoPASCompletedEventHandler alzarArchivoPASCompleted;
        
        /// <remarks/>
        public event listaArchivosPathCompletedEventHandler listaArchivosPathCompleted;
        
        /// <remarks/>
        public event bajarArchivoPASCompletedEventHandler bajarArchivoPASCompleted;
        
        /// <remarks/>
        public event eliminaArchivoPASCompletedEventHandler eliminaArchivoPASCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/extractoCuentaService", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet extractoCuentaService(string usuario, string stringResult, string noise, string lacuenta, string lasFechas_mmddyyyy) {
            object[] results = this.Invoke("extractoCuentaService", new object[] {
                        usuario,
                        stringResult,
                        noise,
                        lacuenta,
                        lasFechas_mmddyyyy});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void extractoCuentaServiceAsync(string usuario, string stringResult, string noise, string lacuenta, string lasFechas_mmddyyyy) {
            this.extractoCuentaServiceAsync(usuario, stringResult, noise, lacuenta, lasFechas_mmddyyyy, null);
        }
        
        /// <remarks/>
        public void extractoCuentaServiceAsync(string usuario, string stringResult, string noise, string lacuenta, string lasFechas_mmddyyyy, object userState) {
            if ((this.extractoCuentaServiceOperationCompleted == null)) {
                this.extractoCuentaServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnextractoCuentaServiceOperationCompleted);
            }
            this.InvokeAsync("extractoCuentaService", new object[] {
                        usuario,
                        stringResult,
                        noise,
                        lacuenta,
                        lasFechas_mmddyyyy}, this.extractoCuentaServiceOperationCompleted, userState);
        }
        
        private void OnextractoCuentaServiceOperationCompleted(object arg) {
            if ((this.extractoCuentaServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.extractoCuentaServiceCompleted(this, new extractoCuentaServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/extractoCuentaConEntidadService", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet extractoCuentaConEntidadService(string usuario, string stringResult, string noise, string lacuenta, string lasFechas_mmddyyyy) {
            object[] results = this.Invoke("extractoCuentaConEntidadService", new object[] {
                        usuario,
                        stringResult,
                        noise,
                        lacuenta,
                        lasFechas_mmddyyyy});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void extractoCuentaConEntidadServiceAsync(string usuario, string stringResult, string noise, string lacuenta, string lasFechas_mmddyyyy) {
            this.extractoCuentaConEntidadServiceAsync(usuario, stringResult, noise, lacuenta, lasFechas_mmddyyyy, null);
        }
        
        /// <remarks/>
        public void extractoCuentaConEntidadServiceAsync(string usuario, string stringResult, string noise, string lacuenta, string lasFechas_mmddyyyy, object userState) {
            if ((this.extractoCuentaConEntidadServiceOperationCompleted == null)) {
                this.extractoCuentaConEntidadServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnextractoCuentaConEntidadServiceOperationCompleted);
            }
            this.InvokeAsync("extractoCuentaConEntidadService", new object[] {
                        usuario,
                        stringResult,
                        noise,
                        lacuenta,
                        lasFechas_mmddyyyy}, this.extractoCuentaConEntidadServiceOperationCompleted, userState);
        }
        
        private void OnextractoCuentaConEntidadServiceOperationCompleted(object arg) {
            if ((this.extractoCuentaConEntidadServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.extractoCuentaConEntidadServiceCompleted(this, new extractoCuentaConEntidadServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/eliminarDirectorio", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eliminarDirectorio(string usuario, string stringResult, string noise, string sucursal, System.DateTime fecha) {
            object[] results = this.Invoke("eliminarDirectorio", new object[] {
                        usuario,
                        stringResult,
                        noise,
                        sucursal,
                        fecha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarDirectorioAsync(string usuario, string stringResult, string noise, string sucursal, System.DateTime fecha) {
            this.eliminarDirectorioAsync(usuario, stringResult, noise, sucursal, fecha, null);
        }
        
        /// <remarks/>
        public void eliminarDirectorioAsync(string usuario, string stringResult, string noise, string sucursal, System.DateTime fecha, object userState) {
            if ((this.eliminarDirectorioOperationCompleted == null)) {
                this.eliminarDirectorioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarDirectorioOperationCompleted);
            }
            this.InvokeAsync("eliminarDirectorio", new object[] {
                        usuario,
                        stringResult,
                        noise,
                        sucursal,
                        fecha}, this.eliminarDirectorioOperationCompleted, userState);
        }
        
        private void OneliminarDirectorioOperationCompleted(object arg) {
            if ((this.eliminarDirectorioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarDirectorioCompleted(this, new eliminarDirectorioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/alzarArchivo", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool alzarArchivo(string usuario, string noise, string stringResult, string path, string extension, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] archivo) {
            object[] results = this.Invoke("alzarArchivo", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path,
                        extension,
                        archivo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void alzarArchivoAsync(string usuario, string noise, string stringResult, string path, string extension, byte[] archivo) {
            this.alzarArchivoAsync(usuario, noise, stringResult, path, extension, archivo, null);
        }
        
        /// <remarks/>
        public void alzarArchivoAsync(string usuario, string noise, string stringResult, string path, string extension, byte[] archivo, object userState) {
            if ((this.alzarArchivoOperationCompleted == null)) {
                this.alzarArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalzarArchivoOperationCompleted);
            }
            this.InvokeAsync("alzarArchivo", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path,
                        extension,
                        archivo}, this.alzarArchivoOperationCompleted, userState);
        }
        
        private void OnalzarArchivoOperationCompleted(object arg) {
            if ((this.alzarArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alzarArchivoCompleted(this, new alzarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/bajarArchivo", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bajarArchivo(string usuario, string noise, string stringResult, string path, string tipo) {
            object[] results = this.Invoke("bajarArchivo", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path,
                        tipo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void bajarArchivoAsync(string usuario, string noise, string stringResult, string path, string tipo) {
            this.bajarArchivoAsync(usuario, noise, stringResult, path, tipo, null);
        }
        
        /// <remarks/>
        public void bajarArchivoAsync(string usuario, string noise, string stringResult, string path, string tipo, object userState) {
            if ((this.bajarArchivoOperationCompleted == null)) {
                this.bajarArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbajarArchivoOperationCompleted);
            }
            this.InvokeAsync("bajarArchivo", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path,
                        tipo}, this.bajarArchivoOperationCompleted, userState);
        }
        
        private void OnbajarArchivoOperationCompleted(object arg) {
            if ((this.bajarArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bajarArchivoCompleted(this, new bajarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/alzarArchivoPAS", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool alzarArchivoPAS(string usuario, string noise, string stringResult, string path, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] archivo) {
            object[] results = this.Invoke("alzarArchivoPAS", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path,
                        archivo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void alzarArchivoPASAsync(string usuario, string noise, string stringResult, string path, byte[] archivo) {
            this.alzarArchivoPASAsync(usuario, noise, stringResult, path, archivo, null);
        }
        
        /// <remarks/>
        public void alzarArchivoPASAsync(string usuario, string noise, string stringResult, string path, byte[] archivo, object userState) {
            if ((this.alzarArchivoPASOperationCompleted == null)) {
                this.alzarArchivoPASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalzarArchivoPASOperationCompleted);
            }
            this.InvokeAsync("alzarArchivoPAS", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path,
                        archivo}, this.alzarArchivoPASOperationCompleted, userState);
        }
        
        private void OnalzarArchivoPASOperationCompleted(object arg) {
            if ((this.alzarArchivoPASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alzarArchivoPASCompleted(this, new alzarArchivoPASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/listaArchivosPath", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] listaArchivosPath(string p_ruta) {
            object[] results = this.Invoke("listaArchivosPath", new object[] {
                        p_ruta});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void listaArchivosPathAsync(string p_ruta) {
            this.listaArchivosPathAsync(p_ruta, null);
        }
        
        /// <remarks/>
        public void listaArchivosPathAsync(string p_ruta, object userState) {
            if ((this.listaArchivosPathOperationCompleted == null)) {
                this.listaArchivosPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaArchivosPathOperationCompleted);
            }
            this.InvokeAsync("listaArchivosPath", new object[] {
                        p_ruta}, this.listaArchivosPathOperationCompleted, userState);
        }
        
        private void OnlistaArchivosPathOperationCompleted(object arg) {
            if ((this.listaArchivosPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaArchivosPathCompleted(this, new listaArchivosPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/bajarArchivoPAS", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bajarArchivoPAS(string usuario, string noise, string stringResult, string path) {
            object[] results = this.Invoke("bajarArchivoPAS", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void bajarArchivoPASAsync(string usuario, string noise, string stringResult, string path) {
            this.bajarArchivoPASAsync(usuario, noise, stringResult, path, null);
        }
        
        /// <remarks/>
        public void bajarArchivoPASAsync(string usuario, string noise, string stringResult, string path, object userState) {
            if ((this.bajarArchivoPASOperationCompleted == null)) {
                this.bajarArchivoPASOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbajarArchivoPASOperationCompleted);
            }
            this.InvokeAsync("bajarArchivoPAS", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path}, this.bajarArchivoPASOperationCompleted, userState);
        }
        
        private void OnbajarArchivoPASOperationCompleted(object arg) {
            if ((this.bajarArchivoPASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bajarArchivoPASCompleted(this, new bajarArchivoPASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://10.1.1.191/extractosService.asmx/eliminaArchivoPAS", RequestNamespace="http://10.1.1.191/extractosService.asmx", ResponseNamespace="http://10.1.1.191/extractosService.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminaArchivoPAS(string usuario, string noise, string stringResult, string path) {
            object[] results = this.Invoke("eliminaArchivoPAS", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminaArchivoPASAsync(string usuario, string noise, string stringResult, string path) {
            this.eliminaArchivoPASAsync(usuario, noise, stringResult, path, null);
        }
        
        /// <remarks/>
        public void eliminaArchivoPASAsync(string usuario, string noise, string stringResult, string path, object userState) {
            if ((this.eliminaArchivoPASOperationCompleted == null)) {
                this.eliminaArchivoPASOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminaArchivoPASOperationCompleted);
            }
            this.InvokeAsync("eliminaArchivoPAS", new object[] {
                        usuario,
                        noise,
                        stringResult,
                        path}, this.eliminaArchivoPASOperationCompleted, userState);
        }
        
        private void OneliminaArchivoPASOperationCompleted(object arg) {
            if ((this.eliminaArchivoPASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminaArchivoPASCompleted(this, new eliminaArchivoPASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void extractoCuentaServiceCompletedEventHandler(object sender, extractoCuentaServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class extractoCuentaServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal extractoCuentaServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void extractoCuentaConEntidadServiceCompletedEventHandler(object sender, extractoCuentaConEntidadServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class extractoCuentaConEntidadServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal extractoCuentaConEntidadServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarDirectorioCompletedEventHandler(object sender, eliminarDirectorioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarDirectorioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarDirectorioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void alzarArchivoCompletedEventHandler(object sender, alzarArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alzarArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alzarArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void bajarArchivoCompletedEventHandler(object sender, bajarArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bajarArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bajarArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void alzarArchivoPASCompletedEventHandler(object sender, alzarArchivoPASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alzarArchivoPASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alzarArchivoPASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void listaArchivosPathCompletedEventHandler(object sender, listaArchivosPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaArchivosPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaArchivosPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void bajarArchivoPASCompletedEventHandler(object sender, bajarArchivoPASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bajarArchivoPASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bajarArchivoPASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminaArchivoPASCompletedEventHandler(object sender, eliminaArchivoPASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminaArchivoPASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminaArchivoPASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591