//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HistoricoMsjSwift_4.sb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="servicebusSoap", Namespace="http://www.bancontinental.com.py/serviceBus")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(claseBaseParametro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(elParametro[]))]
    public partial class servicebus : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback autenticacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback datasetOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback voidCommandOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginUsuarioPruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback blobOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback stringOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback clobOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback dateOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback intOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback doubleOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback intNvarcharOracleOperationCompleted;
        
        private System.Threading.SendOrPostCallback direccionXTelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback F2unaDllOperationCompleted;
        
        private System.Threading.SendOrPostCallback F2unaDllOracle12OperationCompleted;
        
        private System.Threading.SendOrPostCallback F2AlzaEnsambladoOperationCompleted;
        
        private System.Threading.SendOrPostCallback F2FirmaDeUnEnsambladoOperationCompleted;
        
        private System.Threading.SendOrPostCallback F2listaCoincidenciasDLLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public servicebus() {
            this.Url = global::HistoricoMsjSwift_4.Properties.Settings.Default.HistoricoMsjSwift_4_py_com_bancontinental_servicebus_servicebus;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event autenticacionCompletedEventHandler autenticacionCompleted;
        
        /// <remarks/>
        public event datasetOracleCompletedEventHandler datasetOracleCompleted;
        
        /// <remarks/>
        public event voidCommandOracleCompletedEventHandler voidCommandOracleCompleted;
        
        /// <remarks/>
        public event loginUsuarioPruebaCompletedEventHandler loginUsuarioPruebaCompleted;
        
        /// <remarks/>
        public event blobOracleCompletedEventHandler blobOracleCompleted;
        
        /// <remarks/>
        public event stringOracleCompletedEventHandler stringOracleCompleted;
        
        /// <remarks/>
        public event clobOracleCompletedEventHandler clobOracleCompleted;
        
        /// <remarks/>
        public event dateOracleCompletedEventHandler dateOracleCompleted;
        
        /// <remarks/>
        public event intOracleCompletedEventHandler intOracleCompleted;
        
        /// <remarks/>
        public event doubleOracleCompletedEventHandler doubleOracleCompleted;
        
        /// <remarks/>
        public event intNvarcharOracleCompletedEventHandler intNvarcharOracleCompleted;
        
        /// <remarks/>
        public event direccionXTelefonoCompletedEventHandler direccionXTelefonoCompleted;
        
        /// <remarks/>
        public event F2unaDllCompletedEventHandler F2unaDllCompleted;
        
        /// <remarks/>
        public event F2unaDllOracle12CompletedEventHandler F2unaDllOracle12Completed;
        
        /// <remarks/>
        public event F2AlzaEnsambladoCompletedEventHandler F2AlzaEnsambladoCompleted;
        
        /// <remarks/>
        public event F2FirmaDeUnEnsambladoCompletedEventHandler F2FirmaDeUnEnsambladoCompleted;
        
        /// <remarks/>
        public event F2listaCoincidenciasDLLCompletedEventHandler F2listaCoincidenciasDLLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/autenticacion", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBstringAutenticacion autenticacion(string accessPassword, string oracleUser, string oraclePassword, string oracleTns, bool produccion, string noise, string nombreAplicacion) {
            object[] results = this.Invoke("autenticacion", new object[] {
                        accessPassword,
                        oracleUser,
                        oraclePassword,
                        oracleTns,
                        produccion,
                        noise,
                        nombreAplicacion});
            return ((SBstringAutenticacion)(results[0]));
        }
        
        /// <remarks/>
        public void autenticacionAsync(string accessPassword, string oracleUser, string oraclePassword, string oracleTns, bool produccion, string noise, string nombreAplicacion) {
            this.autenticacionAsync(accessPassword, oracleUser, oraclePassword, oracleTns, produccion, noise, nombreAplicacion, null);
        }
        
        /// <remarks/>
        public void autenticacionAsync(string accessPassword, string oracleUser, string oraclePassword, string oracleTns, bool produccion, string noise, string nombreAplicacion, object userState) {
            if ((this.autenticacionOperationCompleted == null)) {
                this.autenticacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautenticacionOperationCompleted);
            }
            this.InvokeAsync("autenticacion", new object[] {
                        accessPassword,
                        oracleUser,
                        oraclePassword,
                        oracleTns,
                        produccion,
                        noise,
                        nombreAplicacion}, this.autenticacionOperationCompleted, userState);
        }
        
        private void OnautenticacionOperationCompleted(object arg) {
            if ((this.autenticacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autenticacionCompleted(this, new autenticacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/datasetOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBdataset datasetOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("datasetOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBdataset)(results[0]));
        }
        
        /// <remarks/>
        public void datasetOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.datasetOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void datasetOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.datasetOracleOperationCompleted == null)) {
                this.datasetOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndatasetOracleOperationCompleted);
            }
            this.InvokeAsync("datasetOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.datasetOracleOperationCompleted, userState);
        }
        
        private void OndatasetOracleOperationCompleted(object arg) {
            if ((this.datasetOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.datasetOracleCompleted(this, new datasetOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/voidCommandOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBstring voidCommandOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("voidCommandOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBstring)(results[0]));
        }
        
        /// <remarks/>
        public void voidCommandOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.voidCommandOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void voidCommandOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.voidCommandOracleOperationCompleted == null)) {
                this.voidCommandOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvoidCommandOracleOperationCompleted);
            }
            this.InvokeAsync("voidCommandOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.voidCommandOracleOperationCompleted, userState);
        }
        
        private void OnvoidCommandOracleOperationCompleted(object arg) {
            if ((this.voidCommandOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.voidCommandOracleCompleted(this, new voidCommandOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/loginUsuarioPrueba", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBbool loginUsuarioPrueba(string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("loginUsuarioPrueba", new object[] {
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBbool)(results[0]));
        }
        
        /// <remarks/>
        public void loginUsuarioPruebaAsync(string ticketResult, string instanciaUnica, string noise) {
            this.loginUsuarioPruebaAsync(ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void loginUsuarioPruebaAsync(string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.loginUsuarioPruebaOperationCompleted == null)) {
                this.loginUsuarioPruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginUsuarioPruebaOperationCompleted);
            }
            this.InvokeAsync("loginUsuarioPrueba", new object[] {
                        ticketResult,
                        instanciaUnica,
                        noise}, this.loginUsuarioPruebaOperationCompleted, userState);
        }
        
        private void OnloginUsuarioPruebaOperationCompleted(object arg) {
            if ((this.loginUsuarioPruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginUsuarioPruebaCompleted(this, new loginUsuarioPruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/blobOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBbyte blobOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("blobOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBbyte)(results[0]));
        }
        
        /// <remarks/>
        public void blobOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.blobOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void blobOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.blobOracleOperationCompleted == null)) {
                this.blobOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnblobOracleOperationCompleted);
            }
            this.InvokeAsync("blobOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.blobOracleOperationCompleted, userState);
        }
        
        private void OnblobOracleOperationCompleted(object arg) {
            if ((this.blobOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.blobOracleCompleted(this, new blobOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/stringOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBstring stringOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("stringOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBstring)(results[0]));
        }
        
        /// <remarks/>
        public void stringOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.stringOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void stringOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.stringOracleOperationCompleted == null)) {
                this.stringOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstringOracleOperationCompleted);
            }
            this.InvokeAsync("stringOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.stringOracleOperationCompleted, userState);
        }
        
        private void OnstringOracleOperationCompleted(object arg) {
            if ((this.stringOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stringOracleCompleted(this, new stringOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/clobOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBstring clobOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("clobOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBstring)(results[0]));
        }
        
        /// <remarks/>
        public void clobOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.clobOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void clobOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.clobOracleOperationCompleted == null)) {
                this.clobOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnclobOracleOperationCompleted);
            }
            this.InvokeAsync("clobOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.clobOracleOperationCompleted, userState);
        }
        
        private void OnclobOracleOperationCompleted(object arg) {
            if ((this.clobOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.clobOracleCompleted(this, new clobOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/dateOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBdate dateOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("dateOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBdate)(results[0]));
        }
        
        /// <remarks/>
        public void dateOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.dateOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void dateOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.dateOracleOperationCompleted == null)) {
                this.dateOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndateOracleOperationCompleted);
            }
            this.InvokeAsync("dateOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.dateOracleOperationCompleted, userState);
        }
        
        private void OndateOracleOperationCompleted(object arg) {
            if ((this.dateOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dateOracleCompleted(this, new dateOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/intOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBint intOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("intOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBint)(results[0]));
        }
        
        /// <remarks/>
        public void intOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.intOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void intOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.intOracleOperationCompleted == null)) {
                this.intOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnintOracleOperationCompleted);
            }
            this.InvokeAsync("intOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.intOracleOperationCompleted, userState);
        }
        
        private void OnintOracleOperationCompleted(object arg) {
            if ((this.intOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.intOracleCompleted(this, new intOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/doubleOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBDouble doubleOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("doubleOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBDouble)(results[0]));
        }
        
        /// <remarks/>
        public void doubleOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.doubleOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void doubleOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.doubleOracleOperationCompleted == null)) {
                this.doubleOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoubleOracleOperationCompleted);
            }
            this.InvokeAsync("doubleOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.doubleOracleOperationCompleted, userState);
        }
        
        private void OndoubleOracleOperationCompleted(object arg) {
            if ((this.doubleOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doubleOracleCompleted(this, new doubleOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/intNvarcharOracle", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBIntNvarchar intNvarcharOracle(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("intNvarcharOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBIntNvarchar)(results[0]));
        }
        
        /// <remarks/>
        public void intNvarcharOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise) {
            this.intNvarcharOracleAsync(llamadaServidor, parametros, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void intNvarcharOracleAsync(string llamadaServidor, elParametro[] parametros, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.intNvarcharOracleOperationCompleted == null)) {
                this.intNvarcharOracleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnintNvarcharOracleOperationCompleted);
            }
            this.InvokeAsync("intNvarcharOracle", new object[] {
                        llamadaServidor,
                        parametros,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.intNvarcharOracleOperationCompleted, userState);
        }
        
        private void OnintNvarcharOracleOperationCompleted(object arg) {
            if ((this.intNvarcharOracleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.intNvarcharOracleCompleted(this, new intNvarcharOracleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/direccionXTelefono", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SBdataset direccionXTelefono(string codigoArea, string numDeTelefono, string ticketResult, string instanciaUnica, string noise) {
            object[] results = this.Invoke("direccionXTelefono", new object[] {
                        codigoArea,
                        numDeTelefono,
                        ticketResult,
                        instanciaUnica,
                        noise});
            return ((SBdataset)(results[0]));
        }
        
        /// <remarks/>
        public void direccionXTelefonoAsync(string codigoArea, string numDeTelefono, string ticketResult, string instanciaUnica, string noise) {
            this.direccionXTelefonoAsync(codigoArea, numDeTelefono, ticketResult, instanciaUnica, noise, null);
        }
        
        /// <remarks/>
        public void direccionXTelefonoAsync(string codigoArea, string numDeTelefono, string ticketResult, string instanciaUnica, string noise, object userState) {
            if ((this.direccionXTelefonoOperationCompleted == null)) {
                this.direccionXTelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndireccionXTelefonoOperationCompleted);
            }
            this.InvokeAsync("direccionXTelefono", new object[] {
                        codigoArea,
                        numDeTelefono,
                        ticketResult,
                        instanciaUnica,
                        noise}, this.direccionXTelefonoOperationCompleted, userState);
        }
        
        private void OndireccionXTelefonoOperationCompleted(object arg) {
            if ((this.direccionXTelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.direccionXTelefonoCompleted(this, new direccionXTelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/F2unaDll", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] F2unaDll(string accessPassword, string noise, string nombreDll) {
            object[] results = this.Invoke("F2unaDll", new object[] {
                        accessPassword,
                        noise,
                        nombreDll});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void F2unaDllAsync(string accessPassword, string noise, string nombreDll) {
            this.F2unaDllAsync(accessPassword, noise, nombreDll, null);
        }
        
        /// <remarks/>
        public void F2unaDllAsync(string accessPassword, string noise, string nombreDll, object userState) {
            if ((this.F2unaDllOperationCompleted == null)) {
                this.F2unaDllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnF2unaDllOperationCompleted);
            }
            this.InvokeAsync("F2unaDll", new object[] {
                        accessPassword,
                        noise,
                        nombreDll}, this.F2unaDllOperationCompleted, userState);
        }
        
        private void OnF2unaDllOperationCompleted(object arg) {
            if ((this.F2unaDllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F2unaDllCompleted(this, new F2unaDllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/F2unaDllOracle12", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] F2unaDllOracle12(string accessPassword, string noise, string nombreDll) {
            object[] results = this.Invoke("F2unaDllOracle12", new object[] {
                        accessPassword,
                        noise,
                        nombreDll});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void F2unaDllOracle12Async(string accessPassword, string noise, string nombreDll) {
            this.F2unaDllOracle12Async(accessPassword, noise, nombreDll, null);
        }
        
        /// <remarks/>
        public void F2unaDllOracle12Async(string accessPassword, string noise, string nombreDll, object userState) {
            if ((this.F2unaDllOracle12OperationCompleted == null)) {
                this.F2unaDllOracle12OperationCompleted = new System.Threading.SendOrPostCallback(this.OnF2unaDllOracle12OperationCompleted);
            }
            this.InvokeAsync("F2unaDllOracle12", new object[] {
                        accessPassword,
                        noise,
                        nombreDll}, this.F2unaDllOracle12OperationCompleted, userState);
        }
        
        private void OnF2unaDllOracle12OperationCompleted(object arg) {
            if ((this.F2unaDllOracle12Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F2unaDllOracle12Completed(this, new F2unaDllOracle12CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/F2AlzaEnsamblado", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string F2AlzaEnsamblado(string accessPassword, string noise, string laDistribucion, string nombreDll, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] ref byte[] ensamblado) {
            object[] results = this.Invoke("F2AlzaEnsamblado", new object[] {
                        accessPassword,
                        noise,
                        laDistribucion,
                        nombreDll,
                        ensamblado});
            ensamblado = ((byte[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void F2AlzaEnsambladoAsync(string accessPassword, string noise, string laDistribucion, string nombreDll, byte[] ensamblado) {
            this.F2AlzaEnsambladoAsync(accessPassword, noise, laDistribucion, nombreDll, ensamblado, null);
        }
        
        /// <remarks/>
        public void F2AlzaEnsambladoAsync(string accessPassword, string noise, string laDistribucion, string nombreDll, byte[] ensamblado, object userState) {
            if ((this.F2AlzaEnsambladoOperationCompleted == null)) {
                this.F2AlzaEnsambladoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnF2AlzaEnsambladoOperationCompleted);
            }
            this.InvokeAsync("F2AlzaEnsamblado", new object[] {
                        accessPassword,
                        noise,
                        laDistribucion,
                        nombreDll,
                        ensamblado}, this.F2AlzaEnsambladoOperationCompleted, userState);
        }
        
        private void OnF2AlzaEnsambladoOperationCompleted(object arg) {
            if ((this.F2AlzaEnsambladoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F2AlzaEnsambladoCompleted(this, new F2AlzaEnsambladoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/F2FirmaDeUnEnsamblado", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string F2FirmaDeUnEnsamblado(string accessPassword, string noise, string laDistribucion, string elArchivo) {
            object[] results = this.Invoke("F2FirmaDeUnEnsamblado", new object[] {
                        accessPassword,
                        noise,
                        laDistribucion,
                        elArchivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void F2FirmaDeUnEnsambladoAsync(string accessPassword, string noise, string laDistribucion, string elArchivo) {
            this.F2FirmaDeUnEnsambladoAsync(accessPassword, noise, laDistribucion, elArchivo, null);
        }
        
        /// <remarks/>
        public void F2FirmaDeUnEnsambladoAsync(string accessPassword, string noise, string laDistribucion, string elArchivo, object userState) {
            if ((this.F2FirmaDeUnEnsambladoOperationCompleted == null)) {
                this.F2FirmaDeUnEnsambladoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnF2FirmaDeUnEnsambladoOperationCompleted);
            }
            this.InvokeAsync("F2FirmaDeUnEnsamblado", new object[] {
                        accessPassword,
                        noise,
                        laDistribucion,
                        elArchivo}, this.F2FirmaDeUnEnsambladoOperationCompleted, userState);
        }
        
        private void OnF2FirmaDeUnEnsambladoOperationCompleted(object arg) {
            if ((this.F2FirmaDeUnEnsambladoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F2FirmaDeUnEnsambladoCompleted(this, new F2FirmaDeUnEnsambladoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bancontinental.com.py/serviceBus/F2listaCoincidenciasDLL", RequestNamespace="http://www.bancontinental.com.py/serviceBus", ResponseNamespace="http://www.bancontinental.com.py/serviceBus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] F2listaCoincidenciasDLL(string accessPassword, string noise, string elArchivo) {
            object[] results = this.Invoke("F2listaCoincidenciasDLL", new object[] {
                        accessPassword,
                        noise,
                        elArchivo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void F2listaCoincidenciasDLLAsync(string accessPassword, string noise, string elArchivo) {
            this.F2listaCoincidenciasDLLAsync(accessPassword, noise, elArchivo, null);
        }
        
        /// <remarks/>
        public void F2listaCoincidenciasDLLAsync(string accessPassword, string noise, string elArchivo, object userState) {
            if ((this.F2listaCoincidenciasDLLOperationCompleted == null)) {
                this.F2listaCoincidenciasDLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnF2listaCoincidenciasDLLOperationCompleted);
            }
            this.InvokeAsync("F2listaCoincidenciasDLL", new object[] {
                        accessPassword,
                        noise,
                        elArchivo}, this.F2listaCoincidenciasDLLOperationCompleted, userState);
        }
        
        private void OnF2listaCoincidenciasDLLOperationCompleted(object arg) {
            if ((this.F2listaCoincidenciasDLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F2listaCoincidenciasDLLCompleted(this, new F2listaCoincidenciasDLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBstringAutenticacion : claseBaseParametro {
        
        private string resultadoField;
        
        private string instanciaUnicaField;
        
        /// <remarks/>
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string instanciaUnica {
            get {
                return this.instanciaUnicaField;
            }
            set {
                this.instanciaUnicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBIntNvarchar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBDouble))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBbyte))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBbool))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBstring))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBdataset))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SBstringAutenticacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class claseBaseParametro {
        
        private errores errorField;
        
        private string elErrorField;
        
        /// <remarks/>
        public errores error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string elError {
            get {
                return this.elErrorField;
            }
            set {
                this.elErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public enum errores {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        credencialesNoValidas,
        
        /// <remarks/>
        errorEnOracle,
        
        /// <remarks/>
        passwordSBErroneo,
        
        /// <remarks/>
        serviceBusNoDisponible,
        
        /// <remarks/>
        inconsitenciaUserDuplicados,
        
        /// <remarks/>
        ticketErroneo,
        
        /// <remarks/>
        idUnicoErroneo,
        
        /// <remarks/>
        noHayConexxionRemota,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class elParametro {
        
        private int tamanhoParametroField;
        
        private tipoDeDatos tipoDatoField;
        
        private object elObjetoField;
        
        private bool esOutField;
        
        private string nombreField;
        
        /// <remarks/>
        public int tamanhoParametro {
            get {
                return this.tamanhoParametroField;
            }
            set {
                this.tamanhoParametroField = value;
            }
        }
        
        /// <remarks/>
        public tipoDeDatos tipoDato {
            get {
                return this.tipoDatoField;
            }
            set {
                this.tipoDatoField = value;
            }
        }
        
        /// <remarks/>
        public object elObjeto {
            get {
                return this.elObjetoField;
            }
            set {
                this.elObjetoField = value;
            }
        }
        
        /// <remarks/>
        public bool esOut {
            get {
                return this.esOutField;
            }
            set {
                this.esOutField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public enum tipoDeDatos {
        
        /// <remarks/>
        indefinido,
        
        /// <remarks/>
        BFile,
        
        /// <remarks/>
        Blob,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        Clob,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Long,
        
        /// <remarks/>
        LongRaw,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        IntervalDS,
        
        /// <remarks/>
        IntervalYM,
        
        /// <remarks/>
        NClob,
        
        /// <remarks/>
        NChar,
        
        /// <remarks/>
        NVarchar2,
        
        /// <remarks/>
        Raw,
        
        /// <remarks/>
        RefCursor,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        TimeStamp,
        
        /// <remarks/>
        TimeStampLTZ,
        
        /// <remarks/>
        TimeStampTZ,
        
        /// <remarks/>
        Varchar2,
        
        /// <remarks/>
        XmlType,
        
        /// <remarks/>
        BinaryDouble,
        
        /// <remarks/>
        BinaryFloat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBIntNvarchar : claseBaseParametro {
        
        private double resultadoIntField;
        
        private string resultadoNvarcharField;
        
        /// <remarks/>
        public double resultadoInt {
            get {
                return this.resultadoIntField;
            }
            set {
                this.resultadoIntField = value;
            }
        }
        
        /// <remarks/>
        public string resultadoNvarchar {
            get {
                return this.resultadoNvarcharField;
            }
            set {
                this.resultadoNvarcharField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBDouble : claseBaseParametro {
        
        private double resultadoField;
        
        /// <remarks/>
        public double resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBint : claseBaseParametro {
        
        private int resultadoField;
        
        /// <remarks/>
        public int resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBdate : claseBaseParametro {
        
        private System.DateTime resultadoField;
        
        /// <remarks/>
        public System.DateTime resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBbyte : claseBaseParametro {
        
        private byte[] resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBbool : claseBaseParametro {
        
        private bool resultadoField;
        
        /// <remarks/>
        public bool resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBstring : claseBaseParametro {
        
        private string resultadoField;
        
        /// <remarks/>
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bancontinental.com.py/serviceBus")]
    public partial class SBdataset : claseBaseParametro {
        
        private System.Data.DataSet resultadoField;
        
        /// <remarks/>
        public System.Data.DataSet resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void autenticacionCompletedEventHandler(object sender, autenticacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autenticacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal autenticacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBstringAutenticacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBstringAutenticacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void datasetOracleCompletedEventHandler(object sender, datasetOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class datasetOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal datasetOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBdataset Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBdataset)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void voidCommandOracleCompletedEventHandler(object sender, voidCommandOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class voidCommandOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal voidCommandOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBstring Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBstring)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void loginUsuarioPruebaCompletedEventHandler(object sender, loginUsuarioPruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginUsuarioPruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginUsuarioPruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBbool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBbool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void blobOracleCompletedEventHandler(object sender, blobOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class blobOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal blobOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBbyte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBbyte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void stringOracleCompletedEventHandler(object sender, stringOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stringOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stringOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBstring Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBstring)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void clobOracleCompletedEventHandler(object sender, clobOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class clobOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal clobOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBstring Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBstring)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void dateOracleCompletedEventHandler(object sender, dateOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dateOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dateOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBdate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBdate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void intOracleCompletedEventHandler(object sender, intOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class intOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal intOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void doubleOracleCompletedEventHandler(object sender, doubleOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doubleOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doubleOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBDouble Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBDouble)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void intNvarcharOracleCompletedEventHandler(object sender, intNvarcharOracleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class intNvarcharOracleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal intNvarcharOracleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBIntNvarchar Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBIntNvarchar)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void direccionXTelefonoCompletedEventHandler(object sender, direccionXTelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class direccionXTelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal direccionXTelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SBdataset Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SBdataset)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void F2unaDllCompletedEventHandler(object sender, F2unaDllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F2unaDllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F2unaDllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void F2unaDllOracle12CompletedEventHandler(object sender, F2unaDllOracle12CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F2unaDllOracle12CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F2unaDllOracle12CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void F2AlzaEnsambladoCompletedEventHandler(object sender, F2AlzaEnsambladoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F2AlzaEnsambladoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F2AlzaEnsambladoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public byte[] ensamblado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void F2FirmaDeUnEnsambladoCompletedEventHandler(object sender, F2FirmaDeUnEnsambladoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F2FirmaDeUnEnsambladoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F2FirmaDeUnEnsambladoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void F2listaCoincidenciasDLLCompletedEventHandler(object sender, F2listaCoincidenciasDLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F2listaCoincidenciasDLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F2listaCoincidenciasDLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591